apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid19
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: covid19
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: covid19
        image: azacrtest.azurecr.io/covid19test:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
       
---
apiVersion: v1
kind: Service
metadata:
  name: covid19
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: covid19

                              
